implement api campaign comment
AnNguyenLe/DonateHope pull request #4
Opened 2024-11-13 14:06 UTC by FangHaiWu

2024-11-14 00:23 UTC, AnNguyenLe commented on src/DonateHope.Core/DTOs/CampaignCommentDTOs/CampaignCommentCreateRequestDto.cs
> +    // public Guid Id { get; set; }
If we don't need it, delete it

2024-11-14 02:55 UTC, AnNguyenLe requested changes

2024-11-14 02:55 UTC, AnNguyenLe commented on src/DonateHope.Core/Services/CampaignCommentsServices/CampaignCommentUpdateService.cs
> +        // updatedCampaignComment.CampaignId = currentCampaignComment.CampaignId;
Comment is not necessary here. Let's delete it

2024-11-14 02:55 UTC, AnNguyenLe commented on src/DonateHope.Core/Services/CampaignCommentsServices/CampaignCommentDeleteService.cs
> +        return _campaignCommentMapper.MapCampaignCommentToCampaignCommentDeleteDto(deletedCampaignComment);
For the the deletion, we don't have to return any value. We just need to know if the delete action was succeeded or not. For such case, these lines:
`deletedCampaignComment.DeletedAt = DateTime.UtcNow;
  deletedCampaignComment.DeletedBy = deletedBy;`
  is no longer necessary.

2024-11-14 02:55 UTC, AnNguyenLe commented on src/DonateHope.WebAPI/Controllers/v1/CampaignComment/CampaignCommentController.cs
> +        return CreatedAtRoute(
This update request does not create a new resource. Using http code 204 should be enough

2024-11-14 02:55 UTC, AnNguyenLe commented on src/DonateHope.WebAPI/Controllers/v1/CampaignComment/CampaignCommentController.cs
> +        return result.Value;
Delete action should not return any value. Http code 200 should be enough. Also, please remove any code related to return the value if any

2024-11-14 02:55 UTC, AnNguyenLe commented on src/DonateHope.WebAPI/DonateHope.WebAPI.csproj
> +    <PackageReference Include="System.Text.Encodings.Web" Version="4.5.1" />
What is the purpose of adding new libs?

2024-11-14 02:55 UTC, AnNguyenLe commented on src/DonateHope.WebAPI/StartupExtensions/DependencyInjectionServicesExtension.cs
>  }
thank you for your hard work!

2024-11-14 02:55 UTC, AnNguyenLe commented on src/DonateHope.Core/Mappers/CampaignCommentMapper.cs
> +    public partial CampaignCommentDeleteDto MapCampaignCommentToCampaignCommentDeleteDto(CampaignComment dto);
Mapper for deletion is not needed. As at the end of the action we just want to know if the delete action succeeded or not

2024-11-14 06:27 UTC, FangHaiWu commented on src/DonateHope.Core/DTOs/CampaignCommentDTOs/CampaignCommentCreateRequestDto.cs
> +    // public Guid Id { get; set; }
Removed it

2024-11-14 06:28 UTC, FangHaiWu commented on src/DonateHope.Core/Services/CampaignCommentsServices/CampaignCommentUpdateService.cs
> +        // updatedCampaignComment.CampaignId = currentCampaignComment.CampaignId;
Removed it

2024-11-14 06:32 UTC, FangHaiWu commented on src/DonateHope.Core/Services/CampaignCommentsServices/CampaignCommentDeleteService.cs
> +        return _campaignCommentMapper.MapCampaignCommentToCampaignCommentDeleteDto(deletedCampaignComment);
Fixed

2024-11-14 06:39 UTC, FangHaiWu commented on src/DonateHope.WebAPI/Controllers/v1/CampaignComment/CampaignCommentController.cs
> +        return CreatedAtRoute(
Revised code.

2024-11-14 06:45 UTC, FangHaiWu commented on src/DonateHope.WebAPI/Controllers/v1/CampaignComment/CampaignCommentController.cs
> +        return result.Value;
Fixed "return result.Value" to "return Ok()"

2024-11-14 08:26 UTC, FangHaiWu commented on src/DonateHope.Core/Services/CampaignCommentsServices/CampaignCommentDeleteService.cs
> +        return _campaignCommentMapper.MapCampaignCommentToCampaignCommentDeleteDto(deletedCampaignComment);
deletedCampaignComment.DeletedAt = DateTime.UtcNow; deletedCampaignComment.DeletedBy = deletedBy;
De luu lai thoi gian xoa

2024-11-14 08:41 UTC, FangHaiWu reviewed
Nhờ Ân check lại

2024-11-15 12:09 UTC, AnNguyenLe approved these changes

2024-11-15 12:10 UTC, merged