Implement APIs for CampaignReport
AnNguyenLe/DonateHope pull request #5
Opened 2024-11-13 15:12 UTC by cungbac

2024-11-14 02:54 UTC, AnNguyenLe requested changes

2024-11-14 02:54 UTC, AnNguyenLe commented on src/DonateHope.Core/Services/CampaignReportServices/CampaignReportDeleteService.cs
> +        return _campaignReportMapper.MapCampaignReportToCampaignReportDeleteResponseDto(deletedCampaignReport);
for deletion, we just want to know if the delete action succeeded or not. We don't have to return any value. Result.Ok() should be enough

2024-11-14 02:54 UTC, AnNguyenLe commented on src/DonateHope.Core/Services/CampaignReportServices/CampaignReportDeleteService.cs
> +        return _campaignReportMapper.MapCampaignReportToCampaignReportDeleteResponseDto(deletedCampaignReport);
also. please remove the the lines of code related to returning deleted value here:
Such as:
at line 45:
deletedCampaignReport.DeletedAt = DateTime.UtcNow;
deletedCampaignReport.DeletedBy = deletedBy;
deletedCampaignReport.ReasonForDeletion = reasonForDeletion;

At mapper for deletion: MapCampaignReportToCampaignReportDeleteResponseDto

2024-11-14 02:54 UTC, AnNguyenLe commented on src/DonateHope.Core/Mappers/CampaignReportMapper.cs
> +    public partial CampaignReportDeleteResponseDto MapCampaignReportToCampaignReportDeleteResponseDto(CampaignReport campaignReport);
No need mapper for delete response

2024-11-14 02:54 UTC, AnNguyenLe commented on src/DonateHope.WebAPI/Controllers/v1/CampaignReport/CampaignReportController.cs
> +        return CreatedAtRoute(
For PUT request, returning 200 should be enough

2024-11-14 02:54 UTC, AnNguyenLe commented on src/DonateHope.WebAPI/Controllers/v1/CampaignReport/CampaignReportController.cs
> +        return result.Value;
For DELETE request, return 200 or 204 should be enough. No need return any value

2024-11-14 02:54 UTC, AnNguyenLe commented on src/DonateHope.WebAPI/StartupExtensions/DependencyInjectionServicesExtension.cs
>  }
Thank for your hard work!

2024-11-14 08:48 UTC, cungbac commented on src/DonateHope.WebAPI/StartupExtensions/DependencyInjectionServicesExtension.cs
>  }
Thanks for your review

2024-11-15 12:28 UTC, cungbac commented on src/DonateHope.Core/Services/CampaignReportServices/CampaignReportDeleteService.cs
> +        return _campaignReportMapper.MapCampaignReportToCampaignReportDeleteResponseDto(deletedCampaignReport);
removed those line of codes

2024-11-15 12:28 UTC, cungbac commented on src/DonateHope.Core/Mappers/CampaignReportMapper.cs
> +    public partial CampaignReportDeleteResponseDto MapCampaignReportToCampaignReportDeleteResponseDto(CampaignReport campaignReport);
mapper deleted

2024-11-15 12:28 UTC, cungbac commented on src/DonateHope.WebAPI/Controllers/v1/CampaignReport/CampaignReportController.cs
> +        return CreatedAtRoute(
returned 200 only

2024-11-15 12:29 UTC, cungbac commented on src/DonateHope.WebAPI/Controllers/v1/CampaignReport/CampaignReportController.cs
> +        return result.Value;
returned 200 only

2024-11-15 12:30 UTC, AnNguyenLe approved these changes

2024-11-15 12:31 UTC, merged